In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [20]:
arr= np.array(mylist)
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr1 = np.array(my_mat)

In [8]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr

array([1, 2, 3])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
arr[2]

3

IndexError: invalid index to scalar variable.

In [23]:
np.arange(0,10).ndim

1

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [25]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.zeros(3).ndim

1

In [27]:
np.zeros((3,3)).ndim

2

In [28]:
np.ones(3)

array([ 1.,  1.,  1.])

In [30]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [37]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [39]:
np.linspace(0,10,10) #np.linspace(0,5,100), one dim has one brackets  , two dims have 2 brackets

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [42]:
np.random.rand(5)

array([ 0.54373599,  0.81132034,  0.04918717,  0.05780349,  0.42000423])

In [41]:
np.random.randn(4,3) #normal distribution

array([[-0.72563777,  0.70596881,  1.58676805],
       [-0.41597153,  0.11044568, -0.08879945],
       [ 1.63440735,  0.44820204, -1.51322622],
       [-0.36616736, -1.70016263, -0.45969745]])

In [43]:
np.random.randint(1,100)

44

In [47]:
np.random.randint(1,100,10)

array([40, 64, 77, 10, 52, 90, 58, 28, 16, 74])

In [48]:
arr = np.arange(25)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,4)

ValueError: total size of new array must be unchanged

In [52]:
 np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr_5 =np.array([1,2,3])

In [55]:
print(type(arr_5))

<class 'numpy.ndarray'>


In [56]:
a1=np.array([])

In [73]:
a_new= np.linspace(1,5,3,dtype='int64')

In [76]:
print(a_new)

[1 3 5]


In [84]:
arr_1 = np.arange(10).reshape(2,5)

In [85]:
arr_1.shape

(2, 5)

In [86]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
a3 = np.array([[1,2,3],[1,3,4],[1,2]])

In [107]:
print(type(a3[0]))

<class 'list'>


In [105]:
a3.shape

(3,)

In [108]:
test_array = np.arange(1000)

In [109]:
test_list = list(range(1000))

In [110]:
%timeit sum(test_list)

100000 loops, best of 3: 7.93 µs per loop


In [111]:
%timeit np.sum(test_array)

The slowest run took 25.15 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.46 µs per loop


In [121]:
a1 =np.array([1,2,3], dtype ='int8')

In [122]:
a1.dtype

dtype('int8')

In [123]:
a1 + 100

array([101, 102, 103], dtype=int8)

In [126]:
a1= a1 + 200

In [127]:
a1

array([201, 202, 203], dtype=int16)

In [128]:
a1 = a1+200

In [129]:
a1

array([401, 402, 403], dtype=int16)

In [176]:
a = np.array([-1,0,1,400],dtype='int8')

In [177]:
a

array([  -1,    0,    1, -112], dtype=int8)

In [178]:
b = np.arange(12).reshape(4,3)

In [179]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [181]:
b[2][2]

8

In [182]:
b[2]

array([6, 7, 8])

In [183]:
b[2,2]

8

In [184]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [185]:
b[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
b[:2,:2]

array([[0, 1],
       [3, 4]])

In [190]:
b[:1,:1]

array([[0]])

In [192]:
b[0,0]

0

In [193]:
res = b[:2,:2]

In [194]:
res

array([[0, 1],
       [3, 4]])

In [195]:
res[0,0] = 100

In [196]:
res

array([[100,   1],
       [  3,   4]])

In [197]:
b

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [198]:
b[1:3,-1]

array([5, 8])

In [200]:
t = b> 5

In [201]:
b[t]

array([100,   6,   7,   8,   9,  10,  11])

In [202]:
t

array([[ True, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [203]:
b[b>5]

array([100,   6,   7,   8,   9,  10,  11])

In [205]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [206]:
a= np.arange(10).reshape(2,5)

In [207]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [213]:
b= np.arange(10)

In [215]:
d = b

In [216]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [211]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [212]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [222]:
b = np.arange(10)

In [223]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [224]:
d=b

In [225]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [242]:
np.array([257],dtype='int8')

array([1], dtype=int8)

In [243]:
np.array([254],dtype='int8')

array([-2], dtype=int8)

In [244]:
np.array([128])

array([128])

In [245]:
np.array([128]).dtype

dtype('int32')

In [246]:
np.array([128],dtype = 'int8')

array([-128], dtype=int8)

In [247]:
np.array([127],dtype = 'int8')

array([127], dtype=int8)

In [248]:
np.array([0],dtype = 'int8')

array([0], dtype=int8)

In [249]:
np.array([-1],dtype = 'int8')

array([-1], dtype=int8)

In [250]:
np.array([-128],dtype = 'int8')

array([-128], dtype=int8)

In [251]:
np.array([-129],dtype = 'int8')

array([127], dtype=int8)

In [252]:
np.array([128],dtype = 'int8')

array([-128], dtype=int8)

In [253]:
np.array([129],dtype = 'int8')

array([-127], dtype=int8)

In [254]:
np.array([254],dtype = 'int8')

array([-2], dtype=int8)

In [255]:
np.array([256],dtype = 'int8')

array([0], dtype=int8)

In [256]:
np.array([257],dtype = 'int8')

array([1], dtype=int8)

In [257]:
np.array([383],dtype = 'int8')

array([127], dtype=int8)

In [259]:
np.array([384],dtype = 'int8')

array([-128], dtype=int8)