##### Numpy Array - Vectors and Matrices

In [80]:
mylist = [1,2,3]

In [81]:
import numpy as np

In [83]:
arr=np.array(mylist)

In [84]:
arr

array([1, 2, 3])

In [85]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [86]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [87]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [92]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [93]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [94]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [95]:
np.ones((3,4)) 

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [97]:
np.linspace(0,5,10) #np.linspace(0,5,100), one dim has one brackets  , two dims have 2 brackets

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [99]:
np.eye(4) #Identity matrix is always square

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [100]:
np.random.rand(5)

array([ 0.79753645,  0.48447308,  0.49327913,  0.83529734,  0.18023587])

In [101]:
np.random.randn(5) #normal distribution

array([ 0.70554387, -1.96744727,  1.43741307, -1.50886696, -0.05228343])

In [102]:
np.random.randn(4,3) #normal distribution

array([[ 1.22586509, -0.49028377,  0.15046488],
       [-0.04671484,  0.58016742, -0.83916229],
       [-0.85809782,  1.51626079, -0.69608819],
       [-0.14450672,  0.25655294, -0.33424288]])

In [103]:
np.random.randint(1,100)

68

In [104]:
np.random.randint(1,100,10)

array([69, 25, 15, 66, 38, 66,  1, 84, 59,  4])

In [105]:
arr = np.arange(25)

In [106]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
arr.max()

24

In [114]:
arr.min()

0

In [116]:
arr.shape

(5, 5)

In [117]:
arr.dtype

dtype('int32')

In [118]:
arr.ndim

2

##### NumPy Indexing and selection

In [119]:
newArr = np.arange(10)

In [121]:
newArr # perform getitem, slice and show that changing the slice changes the original object

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
copyArr= newArr.copy()

In [123]:
copyArr[0] = 100

In [124]:
newArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
copyArr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [126]:
slice_of_Arr = newArr[0:6]

In [127]:
slice_of_Arr[1] = 212

In [128]:
newArr

array([  0, 212,   2,   3,   4,   5,   6,   7,   8,   9])

In [130]:
arr_2d = np.array([[1,2,3],[2,3,4]])

In [131]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [133]:
arr_2d[1,2] #same as arr_2d[1][2]

4

In [136]:
arr_2d[:2,1:]

array([[2, 3],
       [3, 4]])

In [135]:
arr_2d[:1,:1]

array([[1]])

In [137]:
arr = np.arange(1,11)

In [138]:
bool_arr = arr > 5

In [139]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [141]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [142]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [143]:
arr_2d = np.arange(50).reshape(5,10)

In [144]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [147]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

##### Comparison between List and NumpY Execution times

In [ ]:
test_list = list(range(1000))

In [2]:
import numpy as np

In [3]:
test_array = np.arange(1000)

In [4]:
%timeit sum(test_list)

100000 loops, best of 3: 9.53 µs per loop


In [6]:
%timeit np.sum(test_array)

The slowest run took 85.49 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.83 µs per loop


In [7]:
a = np.array([-1,0,1,100],dtype='int8')

In [8]:
a/0

C:\Users\i303440\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Users\i303440\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([-inf,  nan,  inf,  inf])

In [9]:
100**2

10000

In [10]:
10000**2

100000000

In [11]:
a**2

array([ 1,  0,  1, 16], dtype=int8)

In [15]:
a = np.array([-1,0,1,20],dtype='int8')

In [16]:
a**2

array([   1,    0,    1, -112], dtype=int8)

In [17]:
np.zeros

<function numpy.core.multiarray.zeros>

In [18]:
np.ones

<function numpy.core.numeric.ones>

In [19]:
np.empty((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

#### Retreiving the data from array, supports both get item and slice

In [20]:
a = np.array([-1,0,1,100],dtype='int8')

In [21]:
a[0]

-1

In [22]:
 a[-1]

100

In [25]:
a[0:2] #inclusive at lower end and exclusive at higher end and retrieval type will be np array again

array([-1,  0], dtype=int8)

In [26]:
a[:2]

array([-1,  0], dtype=int8)

In [27]:
a[::2]

array([-1,  1], dtype=int8)

In [28]:
a[-1] = 5

In [29]:
b = np.arange(12).reshape(4,3)

In [30]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
a.shape

(4,)

In [32]:
b.shape

(4, 3)

In [34]:
b[2,2] #get item for 2 dim

8

In [38]:
b[:2,:2] #first 2 location in each of the 2 dims

array([[0, 1],
       [3, 4]])

In [42]:
b[1:3,-1]

array([5, 8])

In [43]:
b>1

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [44]:
b[b>1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
b[2]

array([6, 7, 8])

In [52]:
b[2][1]

7

In [55]:
b[2,1]

7

In [63]:
c = np.arange(10)

In [64]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [65]:
c.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [66]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [68]:
c = np.arange(10).reshape(5,2)

In [69]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [74]:
c.ndim

2

In [75]:
c.shape

(5, 2)

thus only arange() and array() functions provides new copy of both header 
and array where as reshape gives only new header