In [11]:
import numpy as np

In [12]:
arr = np.arange(0,6)

In [14]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
arr = np.arange(18)
arr =arr.reshape(3,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [49]:
arr.sum(axis=0)

array([[18, 21, 24],
       [27, 30, 33]])

In [50]:
arr.sum(axis=1)

array([[ 3,  5,  7],
       [15, 17, 19],
       [27, 29, 31]])

In [52]:
arr.sum(axis=2)

array([[ 3, 12],
       [21, 30],
       [39, 48]])

In [44]:
arr = np.arange(36)
arr.reshape(2,3,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]]])

In [16]:
arr = np.arange(72)
arr.reshape(2,2,3,2,3)

array([[[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]],

         [[12, 13, 14],
          [15, 16, 17]]],


        [[[18, 19, 20],
          [21, 22, 23]],

         [[24, 25, 26],
          [27, 28, 29]],

         [[30, 31, 32],
          [33, 34, 35]]]],



       [[[[36, 37, 38],
          [39, 40, 41]],

         [[42, 43, 44],
          [45, 46, 47]],

         [[48, 49, 50],
          [51, 52, 53]]],


        [[[54, 55, 56],
          [57, 58, 59]],

         [[60, 61, 62],
          [63, 64, 65]],

         [[66, 67, 68],
          [69, 70, 71]]]]])

In [18]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr+arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

##### ufunc .. universal function

In [15]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [16]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [17]:
np.max(arr)

10

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [19]:
np.log(arr)

C:\Users\i303440\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [1]:
import numpy as np

In [2]:
arr= np.array([126],dtype='int8')

In [3]:
print(arr)

[126]


In [4]:
arr= np.array([127],dtype='int8')
print(arr)

[127]


In [5]:
arr= np.array([128],dtype='int8')
print(arr)

[-128]


In [6]:
arr= np.array([129],dtype='int8')
print(arr)

[-127]


In [7]:
arr= np.array([-127],dtype='int8')
print(arr)

[-127]


In [8]:
arr= np.array([-128],dtype='int8')
print(arr)

[-128]


In [9]:
arr= np.array([-129],dtype='int8')
print(arr)

[127]


In [10]:
arr= np.array([-130],dtype='int8')
print(arr)

[126]
